import Button from '../../widgets/Button';
import DisplayObject from '../../widgets/DisplayObject';
import Label from '../../widgets/Label';
import Layout from '../../widgets/Layout';
import SeriesLayout from '../../widgets/SeriesLayout';

import ParamsTemplate from '../ParamsTemplate';

// WARNING: This file is auto-generated, DO NOT TOUCH!

// Generated by: /automation/WidgetsBinder.js

/** Provides app developers preloaded widget classes */
export default interface WidgetClasses {
  Button:typeof Button;
	DisplayObject:typeof DisplayObject;
	Label:typeof Label;
	Layout:typeof Layout;
	SeriesLayout:typeof SeriesLayout;
}

export const name = 'widgets';

export const bind = async (params:ParamsTemplate):Promise<WidgetClasses> => {
  return Object.freeze({
    'Button' : Button,
		'DisplayObject' : DisplayObject,
		'Label' : Label,
		'Layout' : Layout,
		'SeriesLayout' : SeriesLayout
  });
}

// Required for /index.m.ts
export const syncBind = (params?:ParamsTemplate):WidgetClasses => {
  return Object.freeze({
    'Button' : Button,
		'DisplayObject' : DisplayObject,
		'Label' : Label,
		'Layout' : Layout,
		'SeriesLayout' : SeriesLayout
  });
}